### PR TITLE
fix: update ci

### PR DESCRIPTION
**Pull request by asvgit**
Hello! In this pull request some fixes have been done:
- Include Ubuntu 18
- Rebuild images with clang
- Fixed check on failures (now it marks job as failed)
- And changes in tests

As I mentioned before, there are some failures from time to time. Should it be an issue? Do you know about that?

### CODE REVIEW

**Comment by asvgit** [comment]
So) I have the same [work with the commit](https://github.com/asvgit/broker/actions/runs/107701747) and it passed successfully)

**Comment by bas524** [comment]
Unfortunately, I don't know about ghost-failures. Let's make it as issue

**Comment by bas524** [comment]
I looked in the log from brokertest, and I think that it was a timeout problem, but we need a proof :-)

Try to increase timeouts in selector-tests

**Comment by bas524** [comment]
Ok, thx!

**Comment by asvgit** [comment]
Indeed, there are time lacks. The broker can start work with messages in a minute after a test has started.

**Pull request merged**
